---
# tasks file for ansible-role-sonar

- name: install unzip
  become: true
  apt: name=unzip state=latest

- name: download sonar
  get_url: url="https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-{{sonaqube_version}}.zip" dest="{{download_directory}}/sonarqube-{{sonaqube_version}}.zip" validate_certs=False


- name: create sonar group
  become: yes
  group: name={{sonar_group}} state=present

- name: create sonar user
  become: yes
  user: name="{{sonar_user}}" group={{sonar_group}} state=present

- name: create dir
  file: path="{{sonar_install_folder}}" state=directory owner="{{sonar_user}}" group="{{sonar_group}}" mode="755"

- name: check if allredy installed
  stat: path="{{sonar_install_folder}}/sonarqube-{{sonaqube_version}}"
  register: installDir


- block:

  - name: untar sonar
    become: yes
    unarchive: src="{{download_directory}}/sonarqube-{{sonaqube_version}}.zip" dest="{{sonar_install_folder}}" copy=no
    notify:
    - restart sonar service

  - name: chown sonardir
    become: true
    file: path="{{sonar_install_folder}}" state=directory owner="{{sonar_user}}" group="{{sonar_group}}" mode="755" recurse=yes

  - name: check if other verion installed
    stat: path="{{sonar_install_folder}}/latest"
    register: latestDir

  - name: install service
    template: src=sonar.service.j2 dest=/lib/systemd/system/sonar.service owner=root mode=755

  - name: stop sonar
    service:
      name: sonar
      state: stopped
    when: latestDir.stat.exists == True

  - name: rename latest to last
    command:  "mv {{sonar_install_folder}}/latest {{sonar_install_folder}}/last"
    when: latestDir.stat.exists == True


  when: installDir.stat.exists == False
